// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import HandController from "./hand_controller"
application.register("hand", HandController)





